version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: socialapp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-semma@2004}
      MYSQL_DATABASE: ${DB_NAME:-socialapp}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - socialapp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-semma@2004}"]
      timeout: 20s
      retries: 10

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: socialapp-backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD:-semma@2004}
      - DB_NAME=${DB_NAME:-socialapp}
      - DB_PORT=3306
      - PORT=5001
    volumes:
      - ./backend/Post_images:/app/Post_images
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - socialapp-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:5001}
    container_name: socialapp-frontend
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - socialapp-network

# Define networks
networks:
  socialapp-network:
    driver: bridge

# Define volumes
volumes:
  mysql_data:
